# Generated by Django 4.2 on 2023-05-02 15:31

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('sender_company', models.CharField(blank=True, default=False, max_length=100)),
                ('sender_pickup_country', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('sender_address', models.CharField(max_length=200)),
                ('sender_address2', models.CharField(blank=True, default=False, max_length=200)),
                ('sender_address3', models.CharField(blank=True, default=False, max_length=200)),
                ('sender_pickup_zip', models.IntegerField(blank=True, null=True)),
                ('sender_city', models.CharField(max_length=100, null=True)),
                ('sender_state', models.CharField(max_length=100, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone_type', models.CharField(max_length=100, null=True)),
                ('sender_phone_code', models.CharField(max_length=10, null=True)),
                ('sender_phone_number', models.CharField(max_length=20, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('receiver_company', models.CharField(blank=True, default=False, max_length=100)),
                ('receiver_delivery_country', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('receiver_address', models.CharField(max_length=200)),
                ('receiver_address2', models.CharField(blank=True, default=False, max_length=200)),
                ('receiver_address3', models.CharField(blank=True, default=False, max_length=200)),
                ('receiver_delivery_zip', models.IntegerField(blank=True, null=True)),
                ('receiver_city', models.CharField(max_length=100, null=True)),
                ('receiver_state', models.CharField(max_length=100, null=True)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone_type', models.CharField(max_length=100, null=True)),
                ('receiver_phone_code', models.CharField(max_length=10, null=True)),
                ('receiver_phone_number', models.CharField(max_length=20, null=True)),
                ('vat_tax_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(default=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(default=False, max_length=100)),
                ('image', models.ImageField(default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_country', models.CharField(max_length=100)),
                ('delivery_country', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_country', models.CharField(default=False, max_length=255)),
                ('delivery_country', models.CharField(default=False, max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('package_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(default=False, max_length=500)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=20)),
                ('card_brand', models.CharField(max_length=20)),
                ('card_expiry_month', models.IntegerField()),
                ('card_expiry_year', models.IntegerField()),
                ('card_cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(default=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(default=False, max_length=100)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_contact', models.CharField(max_length=255)),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_time', models.DateTimeField(default=datetime.datetime(2023, 5, 2, 20, 31, 38, 784657, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(max_length=255)),
                ('origin', models.CharField(default=False, max_length=255, null=True)),
                ('destination', models.CharField(default=False, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipping_type', models.CharField(blank=True, choices=[('documents', 'Documents'), ('packages', 'Packages')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_b', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_state', models.CharField(blank=True, max_length=255, null=True)),
                ('current_country', models.CharField(blank=True, max_length=255, null=True)),
                ('current_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalwis.checkout')),
                ('drop_off_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_shipments', to='globalwis.stations')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalwis.package')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalwis.packaging')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalwis.payment')),
                ('pick_up_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_shipments', to='globalwis.stations')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCountByLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalwis.location')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, default=False, max_length=100)),
                ('country', models.CharField(blank=True, default=False, max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, default=False, max_length=200)),
                ('address3', models.CharField(blank=True, default=False, max_length=200)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_type', models.CharField(max_length=100)),
                ('phone_country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalwis.package'),
        ),
    ]
